import React from 'react'

const Home = () => {
     return(
        <div>
            <br />
            <h1>Welcome! We're glad you're here.</h1>
            <h4>You'll find a collection of books generated by other book worms. Don't be afraid to scroll around and learn what could be very well be your next page turner!</h4>
            <br/>
            <h3>To get started, click on either <strong>VIEW BOOKS</strong> or <strong>ADD A NEW BOOK</strong> and enjoy!</h3>
            <br />
            <br />
        </div>
        
    )
}

export default Home 